INSERT INTO STOCK_SYMBOL values (1, 'CTSH','COGNIZANT');
INSERT INTO STOCK_SYMBOL values (2, 'MSFT','MICROSOFT');
INSERT INTO STOCK_SYMBOL values (3, 'GOOG','GOOGLE');
INSERT INTO STOCK_SYMBOL values (4, 'INFY','INFOSYS');
commit;